apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-flaskapp-config
  labels:
    app.kubernetes.io/name: flaskapp
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
{{ toYaml .Values.configmap.data | indent 2 }}
